// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReservation.Db;

#nullable disable

namespace RestaurantReservation.Db.Migrations
{
    [DbContext(typeof(RestaurantReservationDbContext))]
    [Migration("20241030191624_SecondView")]
    partial class SecondView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantReservation.Db.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "example1@gmail.com",
                            FirstName = "Cus1",
                            LastName = "A",
                            PhoneNumbers = "059900293"
                        },
                        new
                        {
                            Id = 2,
                            Email = "example2@gmail.com",
                            FirstName = "Cus2",
                            LastName = "A",
                            PhoneNumbers = "059900293"
                        },
                        new
                        {
                            Id = 3,
                            Email = "example3@gmail.com",
                            FirstName = "Cus3",
                            LastName = "B",
                            PhoneNumbers = "059900293"
                        },
                        new
                        {
                            Id = 4,
                            Email = "example4@gmail.com",
                            FirstName = "Cus4",
                            LastName = "C",
                            PhoneNumbers = "059900293"
                        },
                        new
                        {
                            Id = 5,
                            Email = "example5@gmail.com",
                            FirstName = "Cus5",
                            LastName = "D",
                            PhoneNumbers = "059900293"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Emp1",
                            LastName = "F",
                            Position = "A",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Emp2",
                            LastName = "B",
                            Position = "A",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Emp3",
                            LastName = "G",
                            Position = "B",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Emp4",
                            LastName = "T",
                            Position = "C",
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Emp5",
                            LastName = "B",
                            Position = "A",
                            RestaurantId = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.EmployeeView", b =>
                {
                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("EmployeesDetails", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Item1",
                            Price = 140.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Item2",
                            Price = 120.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Item3",
                            Price = 130.0,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Item4",
                            Price = 10.0,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Item5",
                            Price = 60.0,
                            RestaurantId = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            OrderDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6320),
                            ReservationId = 1,
                            TotalAmount = 2
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            OrderDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6324),
                            ReservationId = 2,
                            TotalAmount = 12
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            OrderDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6326),
                            ReservationId = 3,
                            TotalAmount = 10
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            OrderDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6329),
                            ReservationId = 4,
                            TotalAmount = 11
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            OrderDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6331),
                            ReservationId = 5,
                            TotalAmount = 120
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 1,
                            OrderId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            MenuItemId = 2,
                            OrderId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            MenuItemId = 3,
                            OrderId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            MenuItemId = 4,
                            OrderId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            MenuItemId = 5,
                            OrderId = 5,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6224),
                            RestaurantId = 1,
                            TableId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6282),
                            RestaurantId = 1,
                            TableId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6286),
                            RestaurantId = 2,
                            TableId = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6288),
                            RestaurantId = 3,
                            TableId = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2024, 10, 30, 21, 16, 23, 621, DateTimeKind.Local).AddTicks(6291),
                            RestaurantId = 5,
                            TableId = 1
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.ReservationView", b =>
                {
                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("ReservationDetails", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpeningHours")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "A",
                            Name = "Res1",
                            OpeningHours = 12,
                            PhoneNumber = "9039741"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "B",
                            Name = "Res2",
                            OpeningHours = 10,
                            PhoneNumber = "9039741"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "D",
                            Name = "Res3",
                            OpeningHours = 6,
                            PhoneNumber = "9039741"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "C",
                            Name = "Res4",
                            OpeningHours = 9,
                            PhoneNumber = "9039741"
                        },
                        new
                        {
                            Id = 5,
                            Adress = "A",
                            Name = "Res5",
                            OpeningHours = 12,
                            PhoneNumber = "9039741"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 5,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 6,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            RestaurantId = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("RestaurantReservation.Db.Models.Reservation", "Reservation")
                        .WithMany("Orders")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId");

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Restaurant", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("MenuItems");

                    b.Navigation("Reservations");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
